# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ferte\Desktop\son.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1340, 680)
        Dialog.setStyleSheet("background-color: rgb(184, 225, 209);\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 20, 260, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setToolTipDuration(-1)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color:rgb(230, 210, 190);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label.setLineWidth(1)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(390, -30, 16, 871))
        self.frame.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(35, 460, 151, 30))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color:rgb(166, 210, 232);\n"
"font-family: \'Helvetica\';\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(35, 520, 151, 30))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background-color:rgb(166, 210, 232);\n"
"font-family: \'Helvetica\';\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(35, 580, 151, 30))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.pushButton_3.setStyleSheet("background-color:rgb(166, 210, 232);\n"
"font-family: \'Helvetica\';\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 399, 121, 31))
        self.label_2.setToolTipDuration(-1)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_2.setLineWidth(1)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(220, 399, 121, 31))
        self.label_3.setToolTipDuration(-1)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_3.setLineWidth(1)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(220, 460, 151, 31))
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setAcceptDrops(False)
        self.comboBox.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 520, 151, 31))
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_2.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(220, 580, 151, 31))
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_3.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(50, 70, 300, 300))
        self.widget.setStyleSheet("border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(490, 20, 161, 31))
        self.label_4.setToolTipDuration(-1)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("background-color:rgb(230, 210, 190);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(730, -40, 16, 871))
        self.frame_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(430, 60, 151, 31))
        self.label_5.setToolTipDuration(-1)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(480, 410, 161, 31))
        self.comboBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_4.setAcceptDrops(False)
        self.comboBox_4.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */\n"
"")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 460, 161, 30))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color:rgb(166, 210, 232);\n"
"font-family: \'Helvetica\';\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(430, 580, 140, 31))
        self.label_13.setToolTipDuration(-1)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_13.setLineWidth(1)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(430, 520, 140, 31))
        self.label_14.setToolTipDuration(-1)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_14.setLineWidth(1)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(430, 100, 151, 31))
        self.label_6.setToolTipDuration(-1)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_6.setLineWidth(1)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(430, 140, 151, 31))
        self.label_7.setToolTipDuration(-1)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_7.setLineWidth(1)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(430, 180, 151, 31))
        self.label_8.setToolTipDuration(-1)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_8.setLineWidth(1)
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(430, 220, 151, 31))
        self.label_9.setToolTipDuration(-1)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_9.setLineWidth(1)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(430, 260, 151, 31))
        self.label_10.setToolTipDuration(-1)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_10.setLineWidth(1)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(430, 300, 151, 31))
        self.label_11.setToolTipDuration(-1)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_11.setLineWidth(1)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(430, 340, 151, 31))
        self.label_12.setToolTipDuration(-1)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_12.setLineWidth(1)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(590, 60, 113, 31))
        self.lineEdit.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(590, 100, 113, 31))
        self.lineEdit_2.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(590, 140, 113, 31))
        self.lineEdit_3.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(590, 180, 113, 31))
        self.lineEdit_4.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_5.setGeometry(QtCore.QRect(590, 220, 113, 31))
        self.lineEdit_5.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_6.setGeometry(QtCore.QRect(590, 260, 113, 31))
        self.lineEdit_6.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_7.setGeometry(QtCore.QRect(590, 300, 113, 31))
        self.lineEdit_7.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_8.setGeometry(QtCore.QRect(590, 340, 113, 31))
        self.lineEdit_8.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(740, 350, 651, 21))
        self.frame_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(980, 20, 161, 31))
        self.label_15.setToolTipDuration(-1)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("background-color:rgb(230, 210, 190);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_15.setLineWidth(1)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(770, 140, 151, 31))
        self.label_16.setToolTipDuration(-1)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_16.setLineWidth(1)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.lineEdit_9 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_9.setGeometry(QtCore.QRect(930, 60, 113, 31))
        self.lineEdit_9.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(770, 100, 151, 31))
        self.label_17.setToolTipDuration(-1)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_17.setLineWidth(1)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(1060, 100, 151, 31))
        self.label_18.setToolTipDuration(-1)
        self.label_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_18.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_18.setLineWidth(1)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.lineEdit_10 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_10.setGeometry(QtCore.QRect(930, 100, 113, 31))
        self.lineEdit_10.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(930, 140, 113, 31))
        self.lineEdit_11.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(770, 220, 151, 31))
        self.label_19.setToolTipDuration(-1)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_19.setLineWidth(1)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.lineEdit_12 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(930, 180, 113, 31))
        self.lineEdit_12.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(930, 220, 113, 31))
        self.lineEdit_13.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(1060, 60, 151, 31))
        self.label_20.setToolTipDuration(-1)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_20.setLineWidth(1)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.lineEdit_14 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_14.setGeometry(QtCore.QRect(930, 260, 113, 31))
        self.lineEdit_14.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(770, 260, 151, 31))
        self.label_21.setToolTipDuration(-1)
        self.label_21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_21.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_21.setLineWidth(1)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.lineEdit_15 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_15.setGeometry(QtCore.QRect(1220, 60, 113, 31))
        self.lineEdit_15.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_15.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(770, 60, 151, 31))
        self.label_22.setToolTipDuration(-1)
        self.label_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_22.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_22.setLineWidth(1)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.lineEdit_16 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_16.setGeometry(QtCore.QRect(1220, 100, 113, 31))
        self.lineEdit_16.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_16.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(770, 180, 151, 31))
        self.label_23.setToolTipDuration(-1)
        self.label_23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_23.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_23.setLineWidth(1)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lineEdit_17 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_17.setGeometry(QtCore.QRect(1220, 140, 113, 31))
        self.lineEdit_17.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_17.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(1060, 140, 151, 31))
        self.label_24.setToolTipDuration(-1)
        self.label_24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_24.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_24.setLineWidth(1)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(1060, 180, 151, 31))
        self.label_25.setToolTipDuration(-1)
        self.label_25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_25.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_25.setLineWidth(1)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.lineEdit_18 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_18.setGeometry(QtCore.QRect(1220, 180, 113, 31))
        self.lineEdit_18.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_18.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_19.setGeometry(QtCore.QRect(1220, 220, 113, 31))
        self.lineEdit_19.setStyleSheet("background-color:rgb(204, 240, 224);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.lineEdit_19.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(1060, 220, 151, 31))
        self.label_26.setToolTipDuration(-1)
        self.label_26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_26.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_26.setLineWidth(1)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(770, 300, 271, 31))
        self.comboBox_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_5.setAcceptDrops(False)
        self.comboBox_5.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */\n"
"")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(1060, 260, 151, 30))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("background-color:rgb(166, 210, 232);\n"
"font-family: \'Helvetica\';\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(1060, 300, 161, 31))
        self.label_27.setToolTipDuration(-1)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_27.setLineWidth(1)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(780, 380, 541, 31))
        self.label_28.setToolTipDuration(-1)
        self.label_28.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_28.setStyleSheet("background-color:rgb(230, 210, 190);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_28.setLineWidth(1)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(780, 420, 331, 31))
        self.comboBox_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_6.setAcceptDrops(False)
        self.comboBox_6.setStyleSheet("background-color:rgb(196, 230, 250);\n"
"font-family: \'Helvetica\';\n"
"font-size: 10px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */\n"
"")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(780, 460, 221, 31))
        self.label_29.setToolTipDuration(-1)
        self.label_29.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_29.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_29.setLineWidth(1)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(780, 495, 221, 31))
        self.label_30.setToolTipDuration(-1)
        self.label_30.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_30.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_30.setLineWidth(1)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(780, 530, 221, 31))
        self.label_31.setToolTipDuration(-1)
        self.label_31.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_31.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_31.setLineWidth(1)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(780, 565, 221, 31))
        self.label_32.setToolTipDuration(-1)
        self.label_32.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_32.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_32.setLineWidth(1)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setGeometry(QtCore.QRect(780, 600, 221, 31))
        self.label_33.setToolTipDuration(-1)
        self.label_33.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_33.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_33.setLineWidth(1)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setGeometry(QtCore.QRect(780, 635, 221, 31))
        self.label_34.setToolTipDuration(-1)
        self.label_34.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_34.setStyleSheet("background-color:rgb(204, 204, 174);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_34.setLineWidth(1)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setGeometry(QtCore.QRect(1120, 420, 200, 191))
        self.widget_2.setStyleSheet("border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(1140, 630, 161, 30))
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("background-color:rgb(166, 210, 232);\n"
"font-family: \'Helvetica\';\n"
"font-size: 13px;\n"
"font-weight: bold;\n"
"border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setGeometry(QtCore.QRect(580, 520, 141, 31))
        self.label_35.setToolTipDuration(-1)
        self.label_35.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_35.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_35.setLineWidth(1)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setGeometry(QtCore.QRect(580, 580, 141, 31))
        self.label_36.setToolTipDuration(-1)
        self.label_36.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_36.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_36.setLineWidth(1)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(Dialog)
        self.label_37.setGeometry(QtCore.QRect(1010, 460, 101, 31))
        self.label_37.setToolTipDuration(-1)
        self.label_37.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_37.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_37.setLineWidth(1)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(Dialog)
        self.label_38.setGeometry(QtCore.QRect(1010, 495, 101, 31))
        self.label_38.setToolTipDuration(-1)
        self.label_38.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_38.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_38.setLineWidth(1)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(Dialog)
        self.label_39.setGeometry(QtCore.QRect(1010, 530, 101, 31))
        self.label_39.setToolTipDuration(-1)
        self.label_39.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_39.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_39.setLineWidth(1)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(Dialog)
        self.label_40.setGeometry(QtCore.QRect(1010, 565, 101, 31))
        self.label_40.setToolTipDuration(-1)
        self.label_40.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_40.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_40.setLineWidth(1)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(Dialog)
        self.label_41.setGeometry(QtCore.QRect(1010, 600, 101, 31))
        self.label_41.setToolTipDuration(-1)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_41.setLineWidth(1)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(Dialog)
        self.label_42.setGeometry(QtCore.QRect(1009, 635, 101, 31))
        self.label_42.setToolTipDuration(-1)
        self.label_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_42.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_42.setLineWidth(1)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(Dialog)
        self.label_43.setGeometry(QtCore.QRect(1230, 300, 101, 31))
        self.label_43.setToolTipDuration(-1)
        self.label_43.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_43.setStyleSheet("background-color:rgb(224, 224, 194);\n"
"font-family: \'Helvetica\';\n"
"font-weight: bold;\n"
"font-size: 13px;border-radius: 12px;          /* Yuvarlatılmış köşeler */\n"
"box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Çıkıntılı 3D etkisi (gölge) */\n"
"border: 2px solid rgb(106, 160, 192);    /* Kenar rengi ve kalınlığı */")
        self.label_43.setLineWidth(1)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Makine Öğrenimi ve Derin Öğrenme ile Çok Fonksiyonlu Hastalık Tespit ve Tanı Sistemi"))
        self.label.setText(_translate("Dialog", "Deri Kanseri ve Beyin Tümörü Tespiti"))
        self.pushButton.setText(_translate("Dialog", "Fotoğraf Yükle"))
        self.pushButton_2.setText(_translate("Dialog", "Fotoğraf Kaydet"))
        self.pushButton_3.setText(_translate("Dialog", "Tespit Yap"))
        self.label_2.setText(_translate("Dialog", "Kanser Durumu:"))
        self.label_3.setText(_translate("Dialog", "Kanser Olasılığı:"))
        self.comboBox.setCurrentText(_translate("Dialog", "Deri Kanseri Tespiti"))
        self.comboBox.setItemText(0, _translate("Dialog", "Deri Kanseri Tespiti"))
        self.comboBox.setItemText(1, _translate("Dialog", "Beyin Tümörü Tespiti"))
        self.comboBox_2.setCurrentText(_translate("Dialog", "Yolov10"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Yolov10"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Yolov8 (Değiştirilmiş Mimari)"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "CNN ile Sınıflandırma"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "VGG16 ile sınıflandırma"))
        self.label_4.setText(_translate("Dialog", "Şeker Hastalığı Tespiti"))
        self.label_5.setText(_translate("Dialog", "Gebelik Sayısı:"))
        self.comboBox_4.setCurrentText(_translate("Dialog", "Logistic Regression"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Logistic Regression"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "K-Nearest Neighbours(KNN)"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Support Vector Machine(SVM)"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "Naive Bayes"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "Decision Tree Classification"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "Random Forest Classification"))
        self.pushButton_4.setText(_translate("Dialog", "Tanı Yap"))
        self.label_13.setText(_translate("Dialog", "Olasılık:"))
        self.label_14.setText(_translate("Dialog", "Şeker Hastalığı:"))
        self.label_6.setText(_translate("Dialog", "Glukoz Konstrasyonu:"))
        self.label_7.setText(_translate("Dialog", "Kan Basıncı:"))
        self.label_8.setText(_translate("Dialog", "Deri Kalınlığı:"))
        self.label_9.setText(_translate("Dialog", "İnsülin Konstrasyonu:"))
        self.label_10.setText(_translate("Dialog", "Vücut Kütle İndeksi:"))
        self.label_11.setText(_translate("Dialog", "Diyabet Soyağacı:"))
        self.label_12.setText(_translate("Dialog", "Yaş:"))
        self.label_15.setText(_translate("Dialog", "Şeker Hastalığı Tespiti"))
        self.label_16.setText(_translate("Dialog", "Göğüs Ağrısı Tipi:"))
        self.label_17.setText(_translate("Dialog", "Cinsiyet:"))
        self.label_18.setText(_translate("Dialog", "Max. Kalp Atış Hızı:"))
        self.label_19.setText(_translate("Dialog", "Kolestrol:"))
        self.label_20.setText(_translate("Dialog", "Elektrokardiyogram:"))
        self.label_21.setText(_translate("Dialog", "Kan Şekeri:"))
        self.label_22.setText(_translate("Dialog", "Yaş:"))
        self.label_23.setText(_translate("Dialog", "Kan Basıncı:"))
        self.label_24.setText(_translate("Dialog", "Egzersiz Anjinası:"))
        self.label_25.setText(_translate("Dialog", "Depresyon:"))
        self.label_26.setText(_translate("Dialog", "ST. Seg. Eğimi:"))
        self.comboBox_5.setCurrentText(_translate("Dialog", "Tensorflow Destekli Yapay Sinir Ağları"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Tensorflow Destekli Yapay Sinir Ağları"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "Pytorch Destekli Yapay Sinir Ağları"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "PCA Destekli Logistic Resgression"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "KNN ve Random Forest Classification ile Birleştirilmiş Algoritma"))
        self.pushButton_5.setText(_translate("Dialog", "Tanı Yap"))
        self.label_27.setText(_translate("Dialog", "Kalp Hastalığı Olasılığı:"))
        self.label_28.setText(_translate("Dialog", "Makine Öğrenmesi Modellerinin Değerlendirilmesi ve Verilerin Görselleştirilmesi"))
        self.comboBox_6.setCurrentText(_translate("Dialog", "Logistic Regression Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "Logistic Regression Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "K-Nearest Neighbours(KNN) Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Support Vector Machine(SVM) Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Naive Bayes Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "Decision Tree Classification Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "Random Forest Classification Tabanlı Şeker Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(6, _translate("Dialog", "Tensorflow Destekli Yapay Sinir Ağlarıyla Kalp Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(7, _translate("Dialog", "PCA Destekli Logistic Regression ile Kalp Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(8, _translate("Dialog", "Birleştirilmiş Tahmin Algoritmasıyla Kalp Hastalığı Sonuçlarının Doğruluk Değerleri"))
        self.comboBox_6.setItemText(9, _translate("Dialog", "Şeker Hastalığı Verilerinin Yaş ve Glukoza Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(10, _translate("Dialog", "Şeker Hastalığı Verilerinin Kan Basıncı ve Glukoza Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(11, _translate("Dialog", "Şeker Hastalarının Kandaki Glukoz Miktarına Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(12, _translate("Dialog", "Şeker Hastalığının Yaşa Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(13, _translate("Dialog", "Kalp Hastalığı Verilerinin Yaş ve Maksimum Kalp Atış Hızına Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(14, _translate("Dialog", "Kalp Hastalığı Verilerinin Kolestrol ve Dinlenme Halindeki Kan Şekerine Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(15, _translate("Dialog", "Kalp Hastalarının Göğüs Ağrı Tiplerine Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(16, _translate("Dialog", "Kalp Hastalığının Cinsiyetlere Göre Görselleştirilmesi"))
        self.comboBox_6.setItemText(17, _translate("Dialog", "Yapay Sinir Ağları ile Kalp Hastalığı Doğruluk Skorlarının Görselleştirilmesi"))
        self.comboBox_6.setItemText(18, _translate("Dialog", "Yapay Sinir Ağları ile Kalp Hastalığı Kayıp Skorlarının Görselleştirilmesi"))
        self.comboBox_6.setItemText(19, _translate("Dialog", "K-Nearest Neighbours(KNN) Tabanlı Şeker Hastalığı Modelinin Komşu Sayısı ile İlişkisinin Görselleştirilmesi"))
        self.comboBox_6.setItemText(20, _translate("Dialog", "K-Nearest Neighbours(KNN) Tabanlı Kalp Hastalığı Modelinin Komşu Sayısı ile İlişkisinin Görselleştirilmesi"))
        self.comboBox_6.setItemText(21, _translate("Dialog", "Random Forest Classification Tabanlı Şeker Hastalığı Modelinin Ağaç Sayısı ile İlişkisinin Görselleştirilmesi"))
        self.comboBox_6.setItemText(22, _translate("Dialog", "Random Forest Classification Tabanlı Kalp Hastalığı Modelinin Ağaç Sayısı ile İlişkisinin Görselleştirilmesi"))
        self.label_29.setText(_translate("Dialog", "Confusion Matrix ile D.S:"))
        self.label_30.setText(_translate("Dialog", "K-Fold Cross Validation ile D.S:"))
        self.label_31.setText(_translate("Dialog", "Prescision Değeri:"))
        self.label_32.setText(_translate("Dialog", "Recall Değeri:"))
        self.label_33.setText(_translate("Dialog", "F1 Skoru:"))
        self.label_34.setText(_translate("Dialog", "Standart Sapma:"))
        self.pushButton_6.setText(_translate("Dialog", "Hesapla"))
        self.label_35.setText(_translate("Dialog", "1"))
        self.label_36.setText(_translate("Dialog", "2"))
        self.label_37.setText(_translate("Dialog", "4"))
        self.label_38.setText(_translate("Dialog", "5"))
        self.label_39.setText(_translate("Dialog", "6"))
        self.label_40.setText(_translate("Dialog", "7"))
        self.label_41.setText(_translate("Dialog", "8"))
        self.label_42.setText(_translate("Dialog", "9"))
        self.label_43.setText(_translate("Dialog", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())